### ISSUE TITLE
Ignore tracking querystrings

### ISSUE THREAD

**Issue by pierremanceaux** [coderedcorp/wagtail-cache#23]
## Status quo
Django full page(s) cache will cache multiple times the same page if different GET parameters are passed.
Example:
- `foo.com/` -> new cache entry
- `foo.com/?do=something` -> new cache entry
- `foo.com/?do=something_else` -> new cache entry

## Why can this be a problem?
First of all, I feel like it's relatively rare these that GET params are changing anything in a page. And if it does, it's something that the developer has under control.
Also, more and more these days, many 3rd parties are polluting our urls and therefore makes it impossible to hit the cached version of a page, even though nothing changes in term of content in the page. There is **many** reasons why random GET params will be appended to your urls!

Example from [here](https://www.wordstream.com/gclid#:~:text=gclid%20tracking%20parameter%20to%20your,of%20a%20particular%20user%20session.):
_A default feature of any Google Ads (formerly known as Google AdWords) account is URL auto-tagging. When this is turned on, Google automatically appends a unique ?gclid tracking parameter to your destination URL whenever someone clicks on one of your ads. Essentially, this is a way for Google Ads to tell Analytics about all the minute details of a particular user session._

You can imagine how big of a problem this can be:
1. The the cache is not hit, so a new cache entry is added.
1. This cache is most likely useless as it is unique to the visitor

## Suggestion(s)
I personally think that we should control this more. Here are a few ideas, up for discussion (please refer to their number when discussing them 🙂)
1. Remove GET parameters from factors that make the cache unique, always return the page as if there was nothing special.
1. Whitelist a few GET parameters keys. If I decide that the key `do_something` should cache a different version of the page, then I have to add it to a certain place (environment variable for instance, like `WAGTAIL_CACHE_GET_PARAMS_WHITELIST = ['key_one', 'key_two']`)
1. Maybe not any page of your website could be affected by these GET parameters, so maybe having a way to whitelist keys directly in a Page Type class definition instead?
1. It could be pushed even further by not only declaring the whitelisted keys, but also a regular expression for the possible values!

## Conclusion
I'm not a Django expert and I can be mistaking somewhere, but so far I'm curious to know what others think about this idea. If not relevant, feel free to close this ticket but please explain why ;)

**Comment by vsalvino** [comment]
Thanks for the detailed suggestion. Based on my knowledge, nearly every cache out there works using the querystring... so I would definitely not want to change this behavior (by default). We are currently using the Django cache middleware utilities to generate the cache keys, which also factors in the querystring.

It could be worth adding a setting to ignore querystrings (Django or Wagtail setting) which works based on your suggestions above. I would be willing to review and help get a pull request merged in if you were to submit one, as long as the behavior is off by default.

**Comment by klausfuchs** [comment]
It is really not beautiful. But then you would have to completely overwrite the method `learn_cache_key `in `django.utils.cache`.

i have solved it for me based on the [solution ](https://github.com/coderedcorp/wagtail-cache/pull/22/commits/1bf3c21dea0510fa60326dec806c0b17e071838b)for page caching. The only problem is that you have duplicate entries in the cache, which can be ignored.

```
from urllib.parse import urljoin, urlparse

url = request.build_absolute_uri()
if wagtailcache_settings.WAGTAIL_CACHE_QUERYS:
   uri = clean_uri(urljoin(url, urlparse(url).path))
else:
   uri = clean_uri(url)
```

**Comment by klausfuchs** [comment]
Another solution might be to edit the `request `object. Maybe so, I have not tested it.

```
if not request.GET._mutable:
   request.GET._mutable = True

request.GET = {}
request.GET._mutable = False
```

**Comment by vsalvino** [comment]
I noticed a similar feature recently appeard in WP Super Cache (WordPress). Their settings let you specify querystrings to ignore during the caching decision. I think a similar feature would be great, and should be pre-populated by default with common tracking code querystrings that are known to seldom be used server-side (such as `utm_*` codes).
