### ISSUE TITLE
Project Future

### ISSUE THREAD

**Issue by klausfuchs** [coderedcorp/wagtail-cache#31]
Is the Project Dead? It wouldn't be nice...

**Comment by vsalvino** [comment]
The project is alive and well. Absence of commits for a few months does not mean the project is dead, only that it is stable.

I know there are some open pull requests for new features, however these will take some time for review and testing. Keep in mind we are a small team and juggle priorities of project work, bug/security fixes, and support for paying customers (this is true of most other open source projects too).

We do appreciate the contributions - the best way to use new features immediately is to install them straight from the branch/fork and test them out in your projects. Eventually they will make their way into the main branch.
