### ISSUE TITLE
Wagtail 5.0 Support

### ISSUE THREAD

**Issue by aliceni81** [coderedcorp/wagtail-cache#51]
Hi, may I know if there will be a release soon for Wagtail 5.0 and Django 4.2?
Thank!

**Comment by sonnybaker** [comment]
Have submitted a PR for this: https://github.com/coderedcorp/wagtail-cache/pull/52

**Comment by aliceni81** [comment]
Thanks @sonnybaker 
@vsalvino Do you have a plan to release it recently?

**Comment by vsalvino** [comment]
Fixed by #52

**Comment by mortenthansen** [comment]
When will a new version of wagtail-cache with this fix be released?
