### ISSUE TITLE
Dependency Conflict Between Wagtail 6 and wagtail-cache 2.3.0

### ISSUE THREAD

**Issue by oleksandr-luxmedien** [coderedcorp/wagtail-cache#64]
## Issue Description

When attempting to lock dependencies with Pipenv in a project using the latest versions of Wagtail (6.0) and wagtail-cache (2.3.0), I encountered a critical dependency resolution failure. This conflict prevents the successful locking of the project's dependencies, hindering the setup and further development of the project.
Environment

- Operating System: Macos Sonoma
- Python Version: 3.12
- Pipenv Version: 2023.12.1

## Steps to Reproduce

Create a new Python project and initialize it with Pipenv.
Add Wagtail 6.0 and wagtail-cache 2.3.0 to the Pipfile:

```
[packages]
wagtail = "==6.0"
wagtail-cache = "==2.3.0"
```

Run pipenv lock to lock the dependencies.

## Expected Behaviour

Pipenv successfully resolves all dependencies and locks them, allowing for the project setup to proceed without issues.
Actual Behaviour

The dependency resolution process fails with a critical error indicating a conflict between Wagtail 6.0 and wagtail-cache 2.3.0. The specific error message is as follows:

```
CRITICAL:pipenv.patched.pip._internal.resolution.resolvelib.factory:Cannot install -r /var/folders/.../pipenv-...-constraints.txt (line 23) and wagtail==6.0 because these package versions have conflicting dependencies.
```

This prevents the successful locking of the project's dependencies.

## Possible Solutions or Suggestions

Investigate the specific dependencies causing the conflict, and explore potential updates or adjustments to wagtail-cache or other related packages that could resolve the issue.
I could try to fix this myself and provide MR with fix, but I'm not sure is this package is actively maintained. 

## Request

I kindly request the maintainers to look into this compatibility issue and provide feedback or a potential roadmap to resolution. Any assistance or guidance on how to navigate this conflict would be greatly appreciated.

**Comment by vsalvino** [comment]
This is due to the fact that Wagtail 6 was just released a few days ago, and we don't yet support it.

I imagine you'll be having a lot of similar issues with your other dependencies. Please keep an eye out until we release wagtail 6 support.
