### ISSUE TITLE
does wagtail-cache cache Django views?

### ISSUE THREAD

**Issue by davidu1975** [coderedcorp/wagtail-cache#79]
does wagtail-cache cache Django views?
As we are seeing Django form views being cached in the Wagtail admin/settings/cache page and was not expecting
this?

**Comment by vsalvino** [comment]
The middleware potentially caches ALL requests/responses of the site. You can set it up to only cache specific views, or ignore specific views. We have detailed documentation on how this works, and how it can be configured: https://docs.coderedcorp.com/wagtail-cache/getting_started/cache_control.html

**Comment by davidu1975** [comment]
thanks
does it cache formviews with csrf tokens and if so how can all formviews be excluded from caching
thanks

**Comment by vsalvino** [comment]
It handles CSRF tokens properly. Please read the documentation which answers your question in detail.
